### PR TITLE
[webpack/rn-compat] Refactor data ingestion

### PR DESCRIPTION
**Pull request by zurawiki**
Avoid use of 'fs' module, use require instead. This allows a client to use this module via webpack, react-native and Browserify.
  - Note that I did have to make minor modifications to the data and dicts files so they could be `require`'d. 
  - I also removed browserify specific config that now is no longer needed since we don't use the `fs` module

I would urge first merging #33 so that the `data/index.js` doesn't have to reach outside of its own directory.

### CODE REVIEW

**Comment by zurawiki** [comment]
CC @nieldlr

**Comment by zurawiki** [comment]
You might want to fetch this commit locally. GitHub doesn't seem to play nicely with the giant dictionary files (It's reporting 100k+ LOC changes). All I did was add the prefix module.exports = \` and suffix  `;

**Comment by zurawiki** [comment]
rebased as well

**Comment by nieldlr** [comment]
Heya @zurawiki, seems we need a fresh rebase for this one. I'd love to pull this down and run some testing briefly if that's okay? So sorry for all my bottle necking here.

**Comment by zurawiki** [comment]
Sure, whatever you need!

**Comment by zurawiki** [comment]
@nieldlr I just rebased again so this PR should be good to merge. Let me know if you need anything else to merge this in

**Comment by nieldlr** [comment]
@zurawiki sorry for my delay! This is looking amazing. Such a neat change too and I like how you brought it in using a separate data index. 👍

**Pull request merged**
