### PR TITLE
Use prettier as linter

### PR DESCRIPTION
**Pull request by zurawiki**
This npm module is really helpful for ensuring that all contributors
maintain the same style guide. Prettier auto-formats all code on commit
so that all commit automatically adhere to the the style guide

The config ignores files in the dict and data directory and does not auto-format them. (see the discussion on #33)

More info about prettier at https://github.com/prettier/prettier

I would love to merge this PR in so that future pull requests do not include many style changes

### CODE REVIEW

**Comment by zurawiki** [comment]
This commit might be easier to review ignoring whitespace

https://github.com/nieldlr/Hanzi/pull/35/files?w=1

**Comment by nieldlr** [comment]
@zurawiki happy to merge this when things have been rebased from the latest PR 👍

**Comment by zurawiki** [comment]
Rebased. All yours!

**Comment by nieldlr** [comment]
This is so great! Tested it locally. Makes following style guides really simple 👍. That pre-commit setup is genius. Merging!

**Pull request merged**
